### ISSUE TITLE
[Bug] Failure to Generate Diff File When diff_file_directory Not Provided

### ISSUE THREAD

**Issue by tina94happy** [KXX-GSS/Diff_Update_Request_Generator#3]
**Description:**
- **Issue:**
  If the `diff_file_directory` parameter is not provided, the application fails to generate the diff file and raises an error.
- **Expected Behavior:**
  The application should generate the diff file in the current path when `diff_file_directory` is not explicitly provided.
- **Additional Issue:**
  When executing the application as an executable (exe), it does not display any log, making it challenging to diagnose the problem.

**Steps to Reproduce:**
1. Input `path_to_initial_file` and `path_to_update_file`.
2. Run the executable (exe).

**Expected Outcome:**
- The diff file should be generated even if `diff_file_directory` is not provided.
- Log information should be displayed during execution when using exe.

**Actual Outcome:**
- The application fails to generate the diff file.
- When executed as an exe, there is no log information.

**Log:**
```
Checking files...
NotADirectoryError: The diff file directory does not exist
```

**Comment by JasonGSS** [comment]
fix
